# O que é o NumPy?
* É uma biblioteca que implementa diversas funções de álgebra linear, como operações vetoriais, cálculos com matrizes etc.
* É a base para um estudo mais aprofundado de algoritmos de aprendizado de máquina e aprendizado profundo.




In [ ]:
import numpy as np

#Criação e Indexação de Arrays

In [ ]:
# CRIA LISTA E ARRAY
v = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_v = np.array(v)

np_v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# CRIA ARRAY UTILIZANDO FUNÇÃO
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Generation

In [ ]:
array1 = np.arange(0, 10) # array range
array1



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array2 = np.arange(0, 10, 2)
array2

array([0, 2, 4, 6, 8])

In [ ]:
zeros1d = np.zeros(5)
print(zeros1d)

[0. 0. 0. 0. 0.]


In [ ]:
ones1d = np.ones(10)
ones1d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
zeros2d = np.zeros((3,4))
zeros2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
my_array = np.linspace(0, 10, 3) # cria array com três números igualmente esparsados, dentre os quais o maior é 10.
my_array

array([ 0.,  5., 10.])

In [ ]:
my_array2 = np.linspace(0, 10, 17)
print(my_array2)

[ 0.     0.625  1.25   1.875  2.5    3.125  3.75   4.375  5.     5.625
  6.25   6.875  7.5    8.125  8.75   9.375 10.   ]


#Criação de Arrays Aleatórios

In [ ]:
my_array = np.random.rand(2, 3)
my_array

array([[0.77916909, 0.37098185, 0.44200408],
       [0.85013279, 0.96850281, 0.48926614]])

In [ ]:
my_array2 = np.random.rand(3)
my_array2

array([0.16727606, 0.95043843, 0.09533955])

In [ ]:
my_array3 = np.random.randn(3) # standard normal distribution (mean = 0, variance = 1)
my_array3

array([-1.15210575,  0.19401273, -0.40359394])

In [ ]:
my_array = np.random.randn(100000) # standard normal distribution (mean = 0, variance = 1)
np.mean(my_array)

0.0045525232099900784

In [ ]:
np.var(my_array)

0.996320323395368

In [ ]:
np.random.randn(2, 3)

array([[-0.22104755,  0.33482788,  0.60729125],
       [-1.13489152,  0.26767344,  1.51338926]])

In [ ]:
np.random.randint(5, 100)

74

array([20, 17, 37, 50])

In [ ]:
np.random.randint(5, 100, (2, 3))

array([[92, 28,  7],
       [26, 57,  6]])

In [ ]:
np.random.seed()
array_seed = np.random.rand(3)
array_seed

array([0.36797948, 0.47173681, 0.68031373])

In [ ]:
array_seed2 = np.random.rand(3)
array_seed2

array([0.62545573, 0.48432148, 0.64025276])

#Redimensionalização


#Operações

In [ ]:
arr1 = np.random.rand(6)
arr1

In [ ]:
arr1.max()

In [ ]:
arr1.argmax()

2

In [ ]:
arr1.min()

In [ ]:
arr1.argmin()

3

In [ ]:
arr1.mean()

In [ ]:
arr1

In [ ]:
arr1.dtype

In [ ]:
arr1 = np.random.rand(5)
arr1


In [ ]:
arr2 = arr1 + 5
arr2

In [ ]:
arr2 - 2


In [ ]:
arr1 + arr2 # arrays must be of the same shape


In [ ]:
arr1 * arr2

In [ ]:
arr1 ** 2

In [ ]:
arr1 / arr2

In [ ]:
arr1 / np.zeros(len(arr1))

In [ ]:
np.zeros(5) / np.zeros(5)

In [ ]:
np.sqrt(arr1)

In [ ]:
np.sin(arr1)

In [ ]:
np.cos(arr1)

In [ ]:
np.log(arr1)

In [ ]:
arr1

In [ ]:
arr1.sum()

In [ ]:
arr1.mean()

In [ ]:
arr1.max()

In [ ]:
arr1.std()

In [ ]:
arr1.var()

In [ ]:
((arr1 - arr1.mean())**2).mean()

In [ ]:
mat1 = np.random.randint(1, 20, (3, 2))
mat1

In [ ]:
mat2 = np.random.randint(5, 15, (2, 4))
mat2

In [ ]:
result = np.matmul(mat1, mat2)
result

In [ ]:
result.shape

(3, 4)

**Operações com Múltiplos Eixos**

In [ ]:
arr1 = np.random.randint(2, 50, (2, 5))
arr1

In [ ]:
arr1.sum()

183

In [ ]:
arr1.sum(axis=0)

In [ ]:
arr1.sum(axis=1)

#Indexação

In [ ]:
arr1 = np.arange(2,11)
arr1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# indexação simples

In [ ]:
# indexação simples(partindo do início)

In [ ]:
# indexação simples(de um ponto até o fim do vetor)

In [ ]:
# atribuição de valor fixo em N elementos

In [ ]:
# atribuição de vetor em N elementos de outro vetor

# Cópia de vetores

In [ ]:
arr1 = np.random.randint(2, 11, 10)
arr1

In [ ]:
arr_copy = arr1.copy()
arr_copy

In [ ]:
slice_arr = arr1[:5]
slice_arr

In [ ]:
slice_arr[:] = -5
slice_arr

In [ ]:
arr1

In [ ]:
arr_copy

##Seleção condicional

# Quebra e concatenação de vetores

In [ ]:
v = np.arange(12)
np.split(v, [3, 5, 6, 10, 11]) # [v[0:3], v[3:5], v[5:6], v[6:10], v[10:11], v[11:]]

In [ ]:
v1, v2, v3, v4, v5, v6 = np.split(v, [3, 5, 6, 10, 11])

In [ ]:
np.concatenate((v1, v2, v3, v4, v5, v6))

# Flatten

In [ ]:
M = np.random.randint(0, 100, (5, 5))
M

In [ ]:
M.ravel() # linha i(0 a 4), coluna j(0 a 4) => indice 5*i + j

##Multiplicação de vetores e matrizes

# Matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()

In [ ]:
plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.xlim([0, 4.0])
plt.ylim([0, 5.0])
plt.show()

In [ ]:
import numpy as np
fig = plt.figure()
ax0 = fig.add_subplot(111)

ax0.plot([0, 1, 2, 3, 4, 5], [0, 1, 4, 9, 16, 25])
ax0.set_ylabel('some numbers')
ax0.set_xlim([0, 4.0])
ax0.set_ylim([0, 4.0])

xticks = np.concatenate((np.arange(0, 1, 0.5), np.arange(1, 5, 0.25)))
yticks = np.concatenate((np.arange(0, 1, 0.5), np.arange(1, 5, 0.25)))

ax0.set_xticks(xticks)
ax0.set_yticks(yticks)
plt.show()

# Gradiente Descendente(Intuição)

In [ ]:
X = np.linspace(-10, 12, 20)
Y = X ** 2 - 2 * X

plt.plot(X, Y)
plt.show()

In [ ]:
def f_Y(x):
  return x ** 2 - 2 * x

def grad_Y(x):
  return 2 * x - 2

In [ ]:
x0 = -10
alfa = 0.2
x_rastro = []
y_rastro = []
for i in range(20):
  x0 = x0 - alfa * grad_Y(x0)
  y0 = f_Y(x0)
  x_rastro.append(x0)
  y_rastro.append(y0)
  print(x0, y0)

In [ ]:
plt.scatter(x_rastro, y_rastro)
plt.plot(X, Y)
plt.show()