# Programação Funcional
### Conjunto de recursos que facilitam a vida do desenvolvedor, mas que podem dificultar a legibilidade do código. Devem ser usados com moderação

# Função Lambda

In [ ]:
def f_def(x):
  return x ** 2

f_def(3)

9

In [ ]:
f_lambda = lambda x: x ** 2
f_lambda(4)

16

In [ ]:
f_odd = lambda x: x % 2 == 1 # x mod 2
f_odd(3)

False

# Map

In [ ]:
import numpy as np

l = [1, 2, 3, 4, 5]
l

[1, 2, 3, 4, 5]

In [ ]:
def f(x):
  return x ** 2

list(map(f, l))

[1, 4, 9, 16, 25]

In [ ]:
list(map(lambda x: x ** 2, l))

[1, 4, 9, 16, 25]

In [ ]:
np.mean(l)

3.0

In [ ]:
list(map(
    lambda x: x - np.mean(l),
    l
))

[-2.0, -1.0, 0.0, 1.0, 2.0]

In [ ]:
list(map(
    lambda x: np.abs(x - np.mean(l)),
    l
))

[2.0, 1.0, 0.0, 1.0, 2.0]

In [ ]:
def min_max_scaler(x):
  return (x - np.min(l))/(np.max(l) - np.min(l))

list(map(min_max_scaler, l))

[0.0, 0.25, 0.5, 0.75, 1.0]

In [ ]:
list(map(lambda x: (x - np.min(l))/(np.max(l) - np.min(l)), l))

[0.0, 0.25, 0.5, 0.75, 1.0]

# Filter

In [ ]:
import numpy as np

v = np.random.randint(1, 10, size=10)
v

array([5, 5, 9, 5, 3, 8, 5, 6, 8, 4])

In [ ]:
v[v>4]

array([5, 5, 9, 5, 8, 5, 6, 8])

In [ ]:
def f(x):
  return x % 2 == 0

list(filter(f, v))

[8, 6, 8, 4]

In [ ]:
list(filter(lambda x: x % 2 == 0, v))

[8, 6, 8, 4]

In [ ]:
v[list(map(lambda x: x%2, v))]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
list(filter(lambda x: x % 2, v))

[5, 5, 9, 5, 3, 5]

In [ ]:
def f_3(x):
  return (x % 3 == 1) or (x % 3 == 2)

list(filter(f_3, v))

[5, 5, 5, 8, 5, 8, 4]

In [ ]:
list(filter(
    lambda x: (x % 3 == 1) or (x % 3 == 2),
    v
))

[5, 5, 5, 8, 5, 8, 4]

# Ordenação Customizada

In [ ]:
# v = [1, 2, 3, 4, 5, 6, 7, 8]
# => [3, 2, 4, 1, 5, 6, 7, 8]
# f(v) => [2, 1, 0, 1, 2, 3, 4, 5] => [0, 1, 1, 2, 2, 3, 4, 5] => v[[0, 1, 1, 2, 2, 3, 4, 5]]

In [ ]:
v4 = [1, 2, 3, 4, 5, 6, 7, 8]
sorted(v4)

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
sorted(v4, key = lambda x: abs(x-3))

[3, 2, 4, 1, 5, 6, 7, 8]

In [ ]:
sorted(v4, key = lambda x: 1/x)

[8, 7, 6, 5, 4, 3, 2, 1]

# Solução da Q01

In [ ]:
x = 3
x % 2 == 0

False

In [ ]:
x % 2

1

In [ ]:
list(filter(lambda x: x%2 == 0, [1, 2, 3, 4]))

[2, 4]

In [ ]:
list(filter(lambda x:not (x%2), [1, 2, 3, 4]))

[2, 4]

#Solução da Q02

In [ ]:
def f(x):
  return x ** 2

list(map(f, l))

[1, 4, 9, 16, 25]

In [ ]:
list(map(lambda x: x ** 2, l))

[1, 4, 9, 16, 25]

#Solução da Q03

In [ ]:
u = [4, 5, 2, 9, 7, 10, 3, 11, 20]

In [ ]:
list(filter(
    lambda x: (x % 4 == 1) or (x % 4 == 2),
    u
))

[5, 2, 9, 10]

In [ ]:
list(filter(
    lambda x: (x % 4 != 3) and (x % 4 != 0),
    u
))

[5, 2, 9, 10]

# Solução da Q04

In [ ]:
l = np.array([3, 4, 1, 8, 2])

In [ ]:
list(map(
    lambda x: np.abs(x - np.median(l)),
    l
))

[2.0, 1.0, 0.0, 1.0, 2.0]

In [ ]:
def f_5(v):
  median = np.median(v)
  for i in range(0, len(v)):
    v[i] = abs(v[i] - median)
  return v

f_5(l)

[2.0, 1.0, 0.0, 1.0, 2.0]