In [ ]:
v = 3
u = 'minha string'

In [ ]:
type(v)

int

In [ ]:
type(u)

str

In [ ]:
lu = [1, 2, 3, 4, 5, 6]
lu

[1, 2, 3, 4, 5, 6]

In [ ]:
lv = [9, 8, 7, 6, 5, 4]
lv

[9, 8, 7, 6, 5, 4]

In [ ]:
# class MinhaClasse:

#   def __add__(self, other):
#     pass

#   def __mul__(self, other):
#     pass

# mc1 = MinhaClasse()
# mc2 = MinhaClasse()

# mc1 + mc2

In [ ]:
type(lv + lu)

list

In [ ]:
lu + lv

[1, 2, 3, 4, 5, 6, 9, 8, 7, 6, 5, 4, 3]

In [ ]:
import numpy as np

In [ ]:
lu = np.array(lu)
lv = np.array(lv)
type(lu)

numpy.ndarray

In [ ]:
print(lu)
print(lv)

[1 2 3 4 5 6]
[9 8 7 6 5 4]


In [ ]:
lu + lv

array([10, 10, 10, 10, 10, 10])

In [ ]:
lu * lv

array([ 9, 16, 21, 24, 25, 24])

# Indexação de arrays

In [ ]:
lu

array([1, 2, 3, 4, 5, 6])

In [ ]:
lu[2]

3

In [ ]:
lu[ [0, 1, 2] ]

array([1, 2, 3])

In [ ]:
lu[ [0, 3, 4, 1] ]

array([1, 4, 5, 2])

In [ ]:
lu

array([1, 2, 3, 4, 5, 6])

In [ ]:
lu[
    [False, True, True, True, False, False]
]

array([2, 3, 4])

In [ ]:
bool_op_1 = lu > 3
bool_op_1

array([False, False, False,  True,  True,  True])

In [ ]:
lu[
    [False, False, False,  True,  True,  True]
]

array([4, 5, 6])

In [ ]:
lu[
    bool_op_1
]

array([4, 5, 6])

In [ ]:
lu[ lu > 3 ]

array([4, 5, 6])

In [ ]:
lu[
    (lu > 2) & (lu < 5)
]

array([3, 4])

In [ ]:
print(lu)
print(lv)

[1 2 3 4 5 6]
[9 8 7 6 5 4]


In [ ]:
lu[0:4] # -> [lu[0], lu[1], lu[2], lu[3]]

array([1, 2, 3, 4])

In [ ]:
lu[1:3]

array([2, 3])

In [ ]:
lu[1:3] * lv[3:5]

array([12, 15])

# Matrizes e Indexação

In [ ]:
m1 = np.array([
    [4, 5, 6],
    [1, 2, 3],
    [7, 6, 2]
])

m2 = np.array([
    [2, 1, 7],
    [7, 6, 2],
    [1, 2, 3]
])

print(m1)
print(m2)

[[4 5 6]
 [1 2 3]
 [7 6 2]]
[[2 1 7]
 [7 6 2]
 [1 2 3]]


In [ ]:
m1

array([[4, 5, 6],
       [1, 2, 3],
       [7, 6, 2]])

In [ ]:
m1[0:2, 0:2]

array([[4, 5],
       [1, 2]])

In [ ]:
m2[1:3, 1:3]

array([[6, 2],
       [2, 3]])

In [ ]:
m2

array([[2, 1, 7],
       [7, 6, 2],
       [1, 2, 3]])

In [ ]:
m2[0:3, 1]

array([1, 6, 2])

In [ ]:
m2[:, 1]

array([1, 6, 2])

In [ ]:
m2[1, 0:3]

array([7, 6, 2])

In [ ]:
m2[1, :]

array([7, 6, 2])

# Geração de Matrizes

In [ ]:
m3 = np.random.randint(1, 37, (3, 3))
m3

array([[ 7, 33,  8],
       [21, 19, 35],
       [ 6, 10, 36]])

In [ ]:
m4 = np.random.randn(5,5)
m4

array([[-0.1048328 , -0.65503107, -0.63208713, -0.74463016,  1.05333545],
       [-0.19331132, -0.08076641,  0.47103048, -0.22521618, -0.54970492],
       [ 0.14940812, -0.527474  , -1.99372204, -0.14723778, -2.37787436],
       [ 0.65467739, -1.84972884, -0.46491058, -1.83544403,  1.30175348],
       [-0.71260169,  0.55260817,  1.21328575, -0.72648019, -0.62470607]])

In [ ]:
m5 = np.random.randn(15,15)
print(m5.mean(), m5.std())

-0.028326910246191626 0.9969155747571943


# Operações com Matrizes

In [ ]:
m6 = np.random.randint(1, 12, (5, 5))
m6

array([[ 6,  1,  1,  9, 11],
       [ 8,  6,  3,  9, 10],
       [ 7,  2,  4, 10,  4],
       [ 8,  9,  5,  2, 10],
       [ 9,  6,  5, 11,  6]])

In [ ]:
m6.sum(axis=1)

array([28, 36, 27, 34, 37])

In [ ]:
m6.sum(axis=0)

array([38, 24, 18, 41, 41])

In [ ]:
m6.mean(axis=1)

array([5.6, 7.2, 5.4, 6.8, 7.4])

In [ ]:
m6.mean(axis=0)

array([7.6, 4.8, 3.6, 8.2, 8.2])

In [ ]:
print(m6.std(axis=1), m6.std(axis=0))

[4.07921561 2.48193473 2.8        2.92574777 2.24499443] [1.0198039  2.92574777 1.49666295 3.18747549 2.71293199]


In [ ]:
m6.sort(axis=1)
m6

array([[ 1,  1,  6,  9, 11],
       [ 3,  6,  8,  9, 10],
       [ 2,  4,  4,  7, 10],
       [ 2,  5,  8,  9, 10],
       [ 5,  6,  6,  9, 11]])

In [ ]:
m6.sort(axis=0)
m6

array([[ 1,  1,  4,  7, 10],
       [ 2,  4,  6,  9, 10],
       [ 2,  5,  6,  9, 10],
       [ 3,  6,  8,  9, 11],
       [ 5,  6,  8,  9, 11]])

# Criar matrizes a partir de outras matrizes

In [ ]:
m5_2 = np.random.randint(1, 5, (3, 6))
m5_2

array([[3, 4, 2, 3, 2, 1],
       [2, 2, 4, 3, 4, 2],
       [3, 2, 4, 1, 3, 3]])

In [ ]:
m5_2.reshape((6, 3))

array([[3, 4, 2],
       [3, 2, 1],
       [2, 2, 4],
       [3, 4, 2],
       [3, 2, 4],
       [1, 3, 3]])

In [ ]:
m5_2.reshape((9, 2))

array([[3, 4],
       [2, 3],
       [2, 1],
       [2, 2],
       [4, 3],
       [4, 2],
       [3, 2],
       [4, 1],
       [3, 3]])

In [ ]:
m5_2.reshape((5, 3))

ValueError: ignored

# Flattenização

In [ ]:
m6.ravel()

array([ 1,  1,  4,  7, 10,  2,  4,  6,  9, 10,  2,  5,  6,  9, 10,  3,  6,
        8,  9, 11,  5,  6,  8,  9, 11])

In [ ]:
m7 = np.random.randint(1, 10, (3, 3, 2))
m7

array([[[9, 8],
        [6, 9],
        [6, 1]],

       [[7, 8],
        [8, 2],
        [8, 7]],

       [[6, 8],
        [2, 3],
        [8, 7]]])

In [ ]:
m7.ravel()

array([9, 8, 6, 9, 6, 1, 7, 8, 8, 2, 8, 7, 6, 8, 2, 3, 8, 7])

In [ ]:
np.concatenate((m7)).shape

(9, 2)

# Subtração ao longo de linhas e colunas

In [ ]:
m8 = np.random.randint(1, 4, (3, 3))
v1 = np.random.randint(1, 3, (1, 3))

print(m8)
print()
print(v1)

[[2 1 2]
 [2 2 2]
 [3 2 3]]

[[2 2 1]]


In [ ]:
m8 - v1
# [2, 1, 2] - [2, 2, 1]
# [2, 2, 2] - [2, 2, 1]
# [3, 2, 3] - [2, 2, 1]

array([[ 0, -1,  1],
       [ 0,  0,  1],
       [ 1,  0,  2]])

In [ ]:
v1 = v1.reshape((3, 1))
v1

array([[2],
       [2],
       [1]])

In [ ]:
m8
# [2, 1, 2] - [2]
# [2, 2, 2] - [2]
# [3, 2, 3] - [1]

array([[2, 1, 2],
       [2, 2, 2],
       [3, 2, 3]])

In [ ]:
m8 - v1

array([[ 0, -1,  0],
       [ 0,  0,  0],
       [ 2,  1,  2]])

# Álgebra Linear

In [ ]:
v = np.random.randint(1, 4, (1, 4))[0]
u = np.random.randint(1, 4, (1, 4))[0]
print(v, u)

[1 2 1 2] [1 2 3 3]


In [ ]:
v.dot(u)
# produto escalar

14

In [ ]:
v = np.array([3, 6, 3])
u = np.array([-1, 1, -1])
v.dot(u)

0

In [ ]:
m10 = np.random.randint(1, 3, (5, 5))
m11 = np.random.randint(1, 3, (5, 5))
m11.dot(m10)

array([[10, 10,  7, 10,  7],
       [10, 10,  7, 10,  7],
       [13, 11,  9, 11,  8],
       [11, 10,  7,  9,  8],
       [14, 12, 10, 14,  9]])

In [ ]:
v2 = np.random.randint(1, 3, (5, 1))
m11.dot(v2)
# (5, 5) x (5, 1) => (5, 1)

array([[ 8],
       [ 8],
       [ 8],
       [ 7],
       [10]])

# Ordenar um array com as posições de outro...

In [ ]:
# v1 = [4, 5, 1, 7, 9]
# v2 = [1, 3, 4, 2, 8]
# após ordenar o v1:
# v1 => [1, 4, 5, 7, 9]
# v2 => [4, 1, 3, 2, 8]

In [ ]:
v1 = np.array([4, 5, 1, 7, 9])
v1.argsort()

array([2, 0, 1, 3, 4])

In [ ]:
v1

array([4, 5, 1, 7, 9])

In [ ]:
v1.sort()
v1

array([1, 4, 5, 7, 9])

In [ ]:
v1[
    [2, 0, 1, 3, 4]
]

array([1, 4, 5, 7, 9])

In [ ]:
v2 = np.array([1, 3, 4, 2, 8])
v2

array([1, 3, 4, 2, 8])

In [ ]:
v2[
    [2, 0, 1, 3, 4]
]

array([4, 1, 3, 2, 8])

In [ ]:
v2[v1.argsort()]

array([4, 1, 3, 2, 8])

In [ ]:
m13 = np.array([1, 2, 3, 5,4])
m13

array([1, 2, 3, 5, 4])

In [ ]:
m13[-3]
# 0 => n-1
# -n+1  <= -1

3

In [ ]:
m13[0:-2]

array([1, 2, 3])

# Resolução de Questões

In [ ]:
# questão 5/9
M = np.random.randint(1, 3, (3, 3))
M

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [ ]:
M.mean(axis=0)

array([1.        , 1.        , 1.33333333])

In [ ]:
M.mean(axis=0).reshape(3, 1)

array([[1.        ],
       [1.        ],
       [1.33333333]])

In [ ]:
M - M.mean(axis=0).reshape(3, 1)
# [1, 1, 1] - [1]
# [1, 1, 1] - [1]
# [1, 1, 2] - [1.3333]

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-0.33333333, -0.33333333,  0.66666667]])

In [ ]:
# Questão 8/9
M = np.random.randint(1, 10, (5, 5))
M

array([[8, 5, 3, 3, 8],
       [9, 7, 6, 2, 4],
       [1, 9, 1, 1, 5],
       [3, 1, 4, 3, 9],
       [3, 5, 8, 8, 7]])

In [ ]:
x = M.ravel()
x.sort()
x

array([1, 1, 1, 1, 2, 3, 3, 3, 3, 3, 4, 4, 5, 5, 5, 6, 7, 7, 8, 8, 8, 8,
       9, 9, 9])

In [ ]:
x.reshape((5, 5))

array([[1, 1, 1, 1, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 5, 5, 5],
       [6, 7, 7, 8, 8],
       [8, 8, 9, 9, 9]])

# Funções Lambda - Python
### Funções que podem ser declaradas em tempo de execução
### Facilitam o desenvolvimento, pois possibilita o uso integrado com map(), filter() e reduce()
### Porém, diminui a legibilidade do código ☹

# Pandas
### Biblioteca para manipulação de dados
### Otimizada para cálculos de grande porte
### Implementa diversos recursos que podem simplificar a vida do desenvolvedor e do analista de dados